### ISSUE TITLE
nuxt graphql client & useState

### ISSUE THREAD

**Issue by cfab** [Diizzayy/nuxt-graphql-client#110]
Hello, 
This is not a bug but a question:
Within composable/states.js I'm trying to use one state in another (need current saison in order to fetch current season spectacles). But I get an error (500 Nuxt instance unavailable) as soon as I use one export in another.
I've done a test with basic fetch here to check if it is possible and indeed it is and works (https://stackblitz.com/edit/nuxt-starter-uxypem?file=composables/states.js)

```js
export const useUser = async () => {
  const data = await $fetch('https://jsonplaceholder.typicode.com/users/');
  return data[2].id;
};

export const useArticles = async () => {
  let userId = await useUser();
  const data = await $fetch(
    `https://jsonplaceholder.typicode.com/posts?userId=${userId}`
  );
  return data;
};
```
Here is the not working code
```js
export const useSiteOptions = async () => {
  const { data } = await useAsyncData("siteOptions", () => GqlSiteOptions());
  let options = data.value.siteOptions.acfOptions;
  return options;
};

export const useSpectacles = async () => {
  // NOT WORKING, WHY ?
  const siteOptions = await useSiteOptions();
  let season = siteOptions.currentSeason.slug;
  console.log(season) // logs correctly '21-22'

  const { data: specs } = await useAsyncData("spectacles", () =>
    GqlSpectaclesBySeason({ terms: season })
  );

  // WORKING IF ABOVE IS COMMENTED
  //   const { data: specs } = await useAsyncData("spectacles", () =>
  //     GqlSpectaclesBySeason({ terms: "21-22" })
  //   );

  return specs.value.spectacles.nodes;
};
```
Here is the full error displayed in the console: 
```
[Vue warn]: Unhandled error during execution of setup function 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/" >
[nuxt] [request error] nuxt instance unavailable
  at Module.useNuxtApp (./.nuxt/dist/server/server.mjs:447:13)  
  at Module.useAsyncData (./.nuxt/dist/server/server.mjs:826:38)  
  at Module.useSpectacles (./.nuxt/dist/server/server.mjs:11050:55)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async setup (./.nuxt/dist/server/server.mjs:14208:12)
```
Any help is welcome, thank you.

**Comment by daniluk4000** [comment]
I experience the same error.

**Comment by Diizzayy** [comment]
@cfab @daniluk4000 This is due to a current limitation of Nuxt3 and inherently Vue 3

The context is lost after the first `await` call, hence any calls to any Nuxt 3 composable (ie: `useState`) or calls to any function that is depending upon context will result in the `nuxt instance unavailable` error.

example: 
```ts
export const useDemo = async () => {
  // wait for a half second
  await new Promise(resolve => setTimeout(() => { resolve(null) }, 500))
  
  // nuxt context is lost after first await call
  // `useState` etc.. will cause 'Nuxt instance unavailable' error

  return useAsyncData(() => $fetch('https://jsonplaceholder.typicode.com/todos/1'))
}
```

A workaround if you must:
```ts
export const useDemo = async () => {
  return useAsyncData(async () => {
    await new Promise(resolve => setTimeout(() => { resolve(null) }, 500))

    return $fetch('https://jsonplaceholder.typicode.com/todos/1')
  })
}
```

**Comment by cfab** [comment]
Thank you very much.
