### ISSUE TITLE
Nuxt error while building `'getSdk' is not exported by .nuxt/gql-sdk.ts`

### ISSUE THREAD

**Issue by Mnigos** [Diizzayy/nuxt-graphql-client#127]
`nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  css: ['vuetify/lib/styles/main.sass', 'mdi/css/materialdesignicons.min.css'],
  build: {
    transpile: ['vuetify', 'chart.js'],
  },
  meta: {...},
  publicRuntimeConfig: {
    lastfmApiKey: process.env.LASTFM_API_KEY,
    apiUrl: process.env.API_URL,
    GQL_HOST: `${process.env.API_URL}/graphql`,
  },
  buildModules: ['@pinia/nuxt'],
  modules: ['nuxt-graphql-client'],
  vite: {
    define: {
      'process.env.DEBUG': false,
    },
  },
  // https://github.com/nuxt/bridge/issues/50
  hooks: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    'vite:extendConfig'(clientConfig: any, { isClient }: any) {
      if (isClient) {
        clientConfig.build.rollupOptions.output.manualChunks = {
          'vue-chartjs': ['vue-chartjs'],
        }
      }
    },
  },
})
```

`dependencies`
```
"nuxt-graphql-client": "^0.0.33",
"nuxt": "3.0.0-rc.3",
```

`full nuxt build output`
```
$ nuxt build
Nuxt CLI v3.0.0-rc.6                                                                        13:21:47

 ERROR  (node:36204) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)


 ERROR  'getSdk' is not exported by .nuxt/gql-sdk.ts, imported by node_modules/nuxt-graphql-client/dist/runtime/composables/index.mjs
file: /node_modules/nuxt-graphql-client/dist/runtime/composables/index.mjs:4:9
2: import { GraphQLClient } from "graphql-request";
3: import { deepmerge } from "../utils.mjs";
4: import { getSdk as gqlSdk } from "#build/gql-sdk";
            ^
5: import { ref, useNuxtApp, useRuntimeConfig, useRequestHeaders } from "#imports";
6: const DEFAULT_STATE = { proxyCookies: true };


 ERROR  'getSdk' is not exported by .nuxt/gql-sdk.ts, imported by node_modules/nuxt-graphql-client/dist/runtime/composables/index.mjs

  at error (node_modules/rollup/dist/shared/rollup.js:198:30)
  at Module.error (node_modules/rollup/dist/shared/rollup.js:12542:16)
  at Module.traceVariable (node_modules/rollup/dist/shared/rollup.js:12901:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/shared/rollup.js:11553:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6486:38)
  at ChildScope.findVariable (node_modules/rollup/dist/shared/rollup.js:6486:38)
  at Identifier.bind (node_modules/rollup/dist/shared/rollup.js:7553:40)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:5383:23)
  at CallExpression.bind (node_modules/rollup/dist/shared/rollup.js:9049:15)
  at VariableDeclarator.bind (node_modules/rollup/dist/shared/rollup.js:5383:23)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Diizzayy** [comment]
@Mnigos Thank you for raising this issue, a PR fixing it should be up in a few minutes
