### ISSUE TITLE
 Unable to load local schema file with codegen.stitchSchemas

### ISSUE THREAD

**Issue by mercs600** [Diizzayy/nuxt-graphql-client#227]
After last changes nuxt is not able to start when my introspection schema is loaded from file. 
It works only when I switch off stitchSchemas 
```js
    codegen: {
      stitchSchemas: false,
    },
```

stack trace:
```bash
 ERROR  Cannot start nuxt:  Unable to load local schema file: app-front/config/introspection.json

  at prepareSchemas (node_modules/nuxt-graphql-client/dist/module.mjs:53:15)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async prepareConfig (node_modules/nuxt-graphql-client/dist/module.mjs:83:47)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:105:18)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:332:22)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:385:5)
  at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:637:5)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:456:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1606:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
```

**Comment by Diizzayy** [comment]
> Is it possible to fetch introspection a moment later - when server is ready ?
We have vite:serverCreated hook - what do you think ?

@mercs600 Great suggestion, I'll look further into this today and determine what's the best approach to run the introspection after the vite server has started ( this would also allow graphql servers to be ran via a nuxt api route - which is currently a limitation of this module )
