### ISSUE TITLE
Error generating when token not provided (version 0.1.27)

### ISSUE THREAD

**Issue by aspitrine** [Diizzayy/nuxt-graphql-client#230]
I have this error when i start my project with the latest version (0.1.27).

I found this line was the cause 

[https://github.com/Diizzayy/nuxt-graphql-client/blob/main/src/module.ts#L83](https://github.com/Diizzayy/nuxt-graphql-client/blob/main/src/module.ts#L83)

More specific `v.token.type` where token is undefined :) 

```
ERROR  Cannot restart nuxt:  Cannot read properties of undefined (reading 'type')                                                                                                                                                       17:15:01

  at setup (node_modules/nuxt-graphql-client/dist/module.mjs:220:76)
  at Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:637:29)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:456:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1606:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6778:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6713:10)

```

Thanks for your hard work

**Comment by Diizzayy** [comment]
@aspitrine Thank you for pointing out this regression! An immediate fix is on the way.
