### ISSUE TITLE
useAsyncData does not work on server side (again?)

### ISSUE THREAD

**Issue by thomas4Bitcraft** [Diizzayy/nuxt-graphql-client#332]
### Environment

- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.4.3
- Nitro Version:    2.4.0
- Package Manager:  npm@8.19.3
- Builder:          vite
- User Config:      app, css, postcss, vue, modules, googleFonts, nitro, i18n, runtimeConfig, graphql-client
- Runtime Modules:  @nuxt/image-edge@1.0.0-28059208.2abef1b, nuxt-graphql-client@0.2.27

### Describe the bug

I have the error again for nuxt 3.4.3 and the version 0.2.27.

This is the component:

```
<template>
    <div>
        <h1 class="text-red-500 text-h1">{{ data?.entry?.modules?.length ?? 0 }}</h1>
    </div>
</template>
<script lang="ts" setup>
const { data, error, refresh } = await useAsyncGql('homepage')

console.log(error.value)
</script>
```
The outputted error is:

```
H3Error                                                                                                                                   
    at Module.createError (file:///xxx/node_modules/h3/dist/index.mjs:128:15)
    at Module.createError (xxx/node_modules/nuxt/dist/app/composables/error.js:37:38)
    at xxx/node_modules/nuxt/dist/app/composables/asyncData.js:80:59
    at <anonymous>
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                      
    at async setup (xxx/pages/index.vue:15:163) {
  statusCode: 500,
  fatal: false,
  unhandled: false,
  statusMessage: undefined,
  __nuxt_error: true
}
```

If I use the same component but add:
```
onMounted(() => {
    refresh()
})
```
the data appears. Any ideas why this is happening?

### Expected behaviour

The data is loaded on server side

**Comment by thomas4Bitcraft** [comment]
Solved - had to call the endpoint via https
