### ISSUE TITLE
Doesn't work on nuxt3 3.0.0-rc.0

### ISSUE THREAD

**Issue by eveningforgery** [Diizzayy/nuxt-graphql-client#39]
```log
Uncaught (in promise) TypeError: Cannot destructure property 'clients' of '(intermediate value)' as it is undefined.
    at getClient (composables.mjs:75:11)
    at useGqlClient (composables.mjs:91:12)
    at useGql (composables.mjs:128:21)
```

Seems like the nuxt team changed how the runtimeConfig works so nuxt-graphql-client is throwing an error as it doesn't find the endpoint.

https://v3.nuxtjs.org/migration/runtime-config/#runtime-config

**Comment by eveningforgery** [comment]
My bad, went a bit too fast there. Thanks!
