### ISSUE TITLE
Not working with Shopify Storefront API

### ISSUE THREAD

**Issue by chrispreisler** [Diizzayy/nuxt-graphql-client#48]
Hey guys,

I am playing around with Nuxt3 and Shopify and started testing out your library. Unfortunately it seems, that it doesn't work with the Shopify Storefront API. Is this because the Shopify Storefront API is not able to give back the types?

I have created a repo here:
https://stackblitz.com/edit/github-pkuqo9-f28qfe?file=nuxt.config.ts

Here is the error I get:

```
 ERROR  Cannot restart nuxt:  Something went wrong Failed to load schema for "gql-sdk.ts"                                                                     11:50:38
        Failed to load schema from https://palavin.myshopify.com/api/unstable/graphql.json:

        Could not obtain introspection result, received: undefined
        Error: Could not obtain introspection result, received: undefined
    at getSchemaFromIntrospection (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/wrap/index.mjs:1798:11)
    at eval (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/wrap/index.mjs:1813:32)
    at async UrlLoader.load (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/url-loader/index.mjs:792:29)
    at async eval (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/load/index.mjs:73:39)
    at async Promise.all (index 5)
    at async loadFile (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/load/index.mjs:71:9)
    at async eval (file:///home/projects/github-pkuqo9-f28qfe/node_modules/@graphql-tools/load/index.mjs:384:25)
    
        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file
    
        Try to use one of above options and run codegen again.
    
      

  Failed to load schema from https://palavin.myshopify.com/api/unstable/graphql.json:
  
  Could not obtain introspection result, received: undefined
  Error: Could not obtain introspection result, received: undefined
  at getSchemaFromIntrospection (node_modules/@graphql-tools/wrap/index.mjs:1798:11)
  at eval (node_modules/@graphql-tools/wrap/index.mjs:1813:32)
  at async UrlLoader.load (node_modules/@graphql-tools/url-loader/index.mjs:792:29)
  at async eval (node_modules/@graphql-tools/load/index.mjs:73:39)
  at async Promise.all (index 5)
  at async loadFile (node_modules/@graphql-tools/load/index.mjs:71:9)
  at async eval (node_modules/@graphql-tools/load/index.mjs:384:25)
  
  GraphQL Code Generator supports:
  - ES Modules and CommonJS exports (export as default or named export "schema")
  - Introspection JSON File
  - URL of GraphQL endpoint
  - Multiple files with type definitions (glob expression)
  - String in config file
  
  Try to use one of above options and run codegen again.
  
  
  at executeCodegen (node_modules/@graphql-codegen/cli/index.mjs:1083:28)
  at async Module.generate (node_modules/@graphql-codegen/cli/index.mjs:1393:25)
  at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:62:10)
  at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:273:22)
  at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:336:5)
  at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:642:5)
  at async Module.installModule (node_modules/@nuxt/kit/dist/index.mjs:457:3)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:1372:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:6749:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:6701:10)
  
  Error: Failed to load schema
  at loadSchema (node_modules/@graphql-codegen/cli/index.mjs:432:15)
  at async eval (node_modules/@graphql-codegen/cli/index.mjs:962:65)
  at async eval (node_modules/@graphql-codegen/cli/index.mjs:961:52)
  at async eval (node_modules/@graphql-codegen/cli/index.mjs:848:21)
```

Thanks so much for looking into that.

The Token ist definetly working.

Best regards
Chris

**Comment by Diizzayy** [comment]
@chrispreisler Thank you for raising this issue and providing the reproduction, it allowed me to pinpoint the issue here.

As you know Shopify uses custom header names for authentication `X-Shopify-Storefront-Access-Token: <YOUR_TOKEN>`. Now the problem here is that current behavior of this module prepends `Bearer` to your access token which then results in a 401 error request hence the failed code generation ( though the request error returned could have been more useful ).

A PR addressing this issue is on the way!

**Comment by Diizzayy** [comment]
@chrispreisler the new version introduces a `type` property to the `token` that defaults to `Bearer`, you can set it to `null` to resolve this issue.

```ts
token: {
  type: null
}
```

**Comment by chrispreisler** [comment]
@Diizzayy thanks so much for looking into it so fast. Now it works like a charme. Thanks so much :)

**Comment by chrispreisler** [comment]
I really like it :) I just ask myself, if it is a bug or normal that it adds 20kb to the "build".
