### ISSUE TITLE
Failed to load schema for "gql-sdk.ts" on deploy

### ISSUE THREAD

**Issue by fskarmeta** [Diizzayy/nuxt-graphql-client#57]
Hello dear developers,

I've managed to create a strapi/graphql/heroku backend that seems to be working fine to me in development mode and also on the local build. But when trying to deploy the Nuxt3/TS app to Netlify or DigitalOcean I've been getting this error. I guess it's probably server-related. 

Any hints would be really appreciated. :)
And thanks for your work !

```
11:21:29 PM: ────────────────────────────────────────────────────────────────
11:21:29 PM:   1. Build command from Netlify app                             
11:21:29 PM: ────────────────────────────────────────────────────────────────
11:21:29 PM: ​
11:21:29 PM: $ yarn build
11:21:29 PM: yarn run v1.22.10
11:21:29 PM: $ nuxi build
11:21:29 PM: [log] Nuxt CLI v3.0.0-rc.1
11:21:35 PM: [error] Something went wrong Failed to load schema for "gql-sdk.ts"
11:21:35 PM:         Failed to load schema from https://catorcentena-graphql.herokuapp.com/graphql:
11:21:35 PM:         Unexpected token P in JSON at position 0
11:21:35 PM:         SyntaxError: Unexpected token P in JSON at position 0
11:21:35 PM:     at JSON.parse (<anonymous>)
11:21:35 PM:     at file:///opt/build/repo/node_modules/@graphql-tools/url-loader/index.mjs:502:37
11:21:35 PM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:21:35 PM:     at async UrlLoader.load (file:///opt/build/repo/node_modules/@graphql-tools/url-loader/index.mjs:776:29)
11:21:35 PM:     at async file:///opt/build/repo/node_modules/@graphql-tools/load/index.mjs:50:39
11:21:35 PM:     at async Promise.all (index 5)
11:21:35 PM:     at async loadFile (file:///opt/build/repo/node_modules/@graphql-tools/load/index.mjs:48:9)
11:21:35 PM:     at async file:///opt/build/repo/node_modules/@graphql-tools/load/index.mjs:361:25
11:21:35 PM:         GraphQL Code Generator supports:
11:21:35 PM:           - ES Modules and CommonJS exports (export as default or named export "schema")
11:21:35 PM:           - Introspection JSON File
11:21:35 PM:           - URL of GraphQL endpoint
11:21:35 PM:           - Multiple files with type definitions (glob expression)
11:21:35 PM:           - String in config file
11:21:35 PM:         Try to use one of above options and run codegen again.
11:21:35 PM:   Failed to load schema from https://catorcentena-graphql.herokuapp.com/graphql:
11:21:35 PM:   Unexpected token P in JSON at position 0
11:21:35 PM:   SyntaxError: Unexpected token P in JSON at position 0
11:21:35 PM:   at JSON.parse (<anonymous>)
11:21:35 PM:   at node_modules/@graphql-tools/url-loader/index.mjs:502:37
11:21:35 PM:   at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:21:35 PM:   at async UrlLoader.load (node_modules/@graphql-tools/url-loader/index.mjs:776:29)
11:21:35 PM:   at async node_modules/@graphql-tools/load/index.mjs:50:39
11:21:35 PM:   at async Promise.all (index 5)
11:21:35 PM:   at async loadFile (node_modules/@graphql-tools/load/index.mjs:48:9)
11:21:35 PM:   at async node_modules/@graphql-tools/load/index.mjs:361:25
11:21:35 PM:   GraphQL Code Generator supports:
11:21:35 PM:   - ES Modules and CommonJS exports (export as default or named export "schema")
11:21:35 PM:   - Introspection JSON File
11:21:35 PM:   - URL of GraphQL endpoint
11:21:35 PM:   - Multiple files with type definitions (glob expression)
11:21:35 PM:   - String in config file
11:21:35 PM:   Try to use one of above options and run codegen again.
11:21:35 PM:   at executeCodegen (node_modules/@graphql-codegen/cli/index.mjs:1051:28)
11:21:35 PM:   at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:21:35 PM:   at async generate (node_modules/@graphql-codegen/cli/index.mjs:1361:25)
11:21:35 PM:   at async generate (node_modules/nuxt-graphql-client/dist/module.mjs:57:10)
11:21:35 PM:   at async generateGqlTypes (node_modules/nuxt-graphql-client/dist/module.mjs:277:22)
11:21:35 PM:   at async setup (node_modules/nuxt-graphql-client/dist/module.mjs:340:5)
11:21:35 PM:   at async Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:577:5)
11:21:35 PM:   at async installModule (node_modules/@nuxt/kit/dist/index.mjs:392:3)
11:21:35 PM:   at async initNuxt (node_modules/nuxt/dist/index.mjs:1362:7)
11:21:35 PM:   at async loadNuxt (node_modules/nuxt/dist/index.mjs:1384:5)
11:21:35 PM:   Error: Failed to load schema
11:21:35 PM:   at loadSchema (node_modules/@graphql-codegen/cli/index.mjs:400:15)
11:21:35 PM:   at processTicksAndRejections (node:internal/process/task_queues:96:5)
11:21:35 PM:   at async node_modules/@graphql-codegen/cli/index.mjs:930:65
11:21:35 PM:   at async node_modules/@graphql-codegen/cli/index.mjs:929:52
11:21:35 PM:   at async node_modules/@graphql-codegen/cli/index.mjs:816:21
11:21:35 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
11:21:35 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Diizzayy** [comment]
@fskarmeta Thank you for raising this issue, though I've not been able to reproduce this occurrence on my end [netlify minimal demo](https://bespoke-jelly-5207b6.netlify.app)

Would you be able to produce a reproduction so I can see exactly where the cause might be?

**Comment by fskarmeta** [comment]
@Diizzayy oh that's good to hear.. so probably I'm doing something wrong.

https://github.com/fskarmeta/catorcentena-frontend just made it public for you to see since its WIP :d

**Comment by Diizzayy** [comment]
@fskarmeta I'll have a look now

**Comment by fskarmeta** [comment]
@Diizzayy thank you very much :) !

**Comment by Diizzayy** [comment]
@fskarmeta I wasn't able to pinpoint the issue here but I suspect it was caused by a mismatch of dependencies due to locked older versions your `yarn.lock` file.

Simply deleting that file then running `yarn install` resolved the issues on my end

**Comment by fskarmeta** [comment]
@Diizzayy yes.. that solved that issue! I should have tried that out before. Thanks so much for your time! Really appreciate it

**Comment by Diizzayy** [comment]
@fskarmeta No problem at all, I'm happy to help.
