### ISSUE TITLE
bug(pnpm): require() of ES Module

### ISSUE THREAD

**Issue by ririen** [Diizzayy/nuxt-graphql-client#68]
With `pnpm` after` pnpm build` and then `pnpm preview` crashes with strange errors. With `yarn` everything works fine.

------------------------------
- Operating System: `Linux`
- Node Version:     `v18.1.0`
- Nuxt Version:     `3.0.0-rc.3`
- Package Manager:  `pnpm@7.0.1`
- Builder:          `vite`
- User Config:      `runtimeConfig`, `css`, `modules`, `vueuse`, `schemaOrg`, `unocss`, `experimental`
- Runtime Modules:  `@vueuse/nuxt@8.4.2`, `@unocss/nuxt@0.33.2`, `nuxt-schema-org@0.5.2`, `nuxt-graphql-client@0.0.25`
- Build Modules:    `-`
------------------------------

```sh
[nuxt] [request error] require() of ES Module /home/ririen/Projekty/Project/Website/.output/server/node_modules/node-fetch/src/index.js from /home/ririen/Projekty/Project/Website/.output/server/node_modules/cross-fetch/dist/node-ponyfill.js not supported.
Instead change the require of index.js in /home/ririen/Project/Project/Website/.output/server/node_modules/cross-fetch/dist/node-ponyfill.js to a dynamic import() which is available in all CommonJS modules.
  at Object.<anonymous> (./server/node_modules/cross-fetch/dist/node-ponyfill.js:1:19)  
  at Object.<anonymous> (./server/node_modules/graphql-request/dist/index.js:84:34)  
  at async Promise.all (index 0)  
  at async ./server/chunks/handlers/renderer.mjs:11064:24  
  at async ./server/chunks/handlers/renderer.mjs:11120:64  
  at async ./server/node_modules/h3/dist/index.mjs:417:19  
  at async Server.nodeHandler (./server/node_modules/h3/dist/index.mjs:367:7)
```

**Comment by DenisNikonov** [comment]
i get this error with `yarn` after `yarn preview` or `node .output/server/index.mjs` 

```
(node:95748) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/denisnikonov/projects/nuxt-text/.output/server/node_modules/node-fetch/src/index.js:9
import http from 'node:http';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)

Node.js v18.1.0
```

**Comment by Diizzayy** [comment]
@ririen @DenisNikonov This was addressed upstream and should now be working without issue for you.

_be sure to delete your lockfile (`yarn.lock` or `package-lock.json`) and ensure that your new lockfile uses `unenv >= 0.5.2`, this can be verified for yarn by running `yarn why unenv`_

**Comment by DenisNikonov** [comment]
@Diizzayy It works! Thank you for your work
